{{- if .Values.jwtSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nitro.fullname" . }}-jwt
  labels:
    {{- include "nitro.labels" . | nindent 4 }}
data:
  jwtSecret: {{ .Values.jwtSecret.value | b64enc | quote }}
{{- end }}